services:
  api:
    build: &app-image
      context: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    # command: "sh -c 'uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'"
    # command: "sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 3 --host 0.0.0.0 --port 8000'"
    # command: "sh -c 'alembic upgrade head && python app/initial_data.py && gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes: &app-vol
      - .:/app
    env_file: &envfile
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    expose:
      - "6379"
